// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
import java.util.*;
class Main {
   public static void main(String args[]) throws Exception {
    MyTree t = new MyTree();
    t.load();
    int choice;
    Scanner sca = new Scanner(System.in);
    System.out.println();
    System.out.println(" 1. Test f1 - compute height");
    System.out.println(" 2. Test f2 - count nodes");
    System.out.println(" 3. Test f3 - count leaf nodes");
    System.out.println(" 4. Test f4 - compute sum of nodes ");
    System.out.print("    Your selection (1 -> 4): ");
    choice = sca.nextInt();
    sca.nextLine();
    int r;
    switch(choice) {
       case 1: 
           System.out.println("Height:");
           r = t.f1();
           System.out.println(r);
           break;
       case 2: 
           System.out.println("Count nodes:");
           r = t.f2();
           System.out.println(r);
           break;
       case 3: 
           System.out.println("Count leaf nodes:");
           r = t.f3();
           System.out.println(r);
           break;
          case 4: 
           System.out.println("Sum of nodes:");
           r = t.f4();
           System.out.println(r);
           break;
       default: System.out.println("Wrong selection");
      }
     System.out.println();
   }      
 }
